// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: proto/v1/auth.proto

package totp_auth_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateTOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
}

func (x *GenerateTOTPRequest) Reset() {
	*x = GenerateTOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTOTPRequest) ProtoMessage() {}

func (x *GenerateTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTOTPRequest.ProtoReflect.Descriptor instead.
func (*GenerateTOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTOTPRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type GenerateTOTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GenerateTOTPResponse) Reset() {
	*x = GenerateTOTPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTOTPResponse) ProtoMessage() {}

func (x *GenerateTOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTOTPResponse.ProtoReflect.Descriptor instead.
func (*GenerateTOTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTOTPResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ValidateTOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *ValidateTOTPRequest) Reset() {
	*x = ValidateTOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTOTPRequest) ProtoMessage() {}

func (x *ValidateTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTOTPRequest.ProtoReflect.Descriptor instead.
func (*ValidateTOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTOTPRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTOTPRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ValidateTOTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *ValidateTOTPResponse) Reset() {
	*x = ValidateTOTPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateTOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTOTPResponse) ProtoMessage() {}

func (x *ValidateTOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTOTPResponse.ProtoReflect.Descriptor instead.
func (*ValidateTOTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTOTPResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_v1_auth_proto protoreflect.FileDescriptor

var file_proto_v1_auth_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x64, 0x71, 0x78, 0x30, 0x2e, 0x74, 0x6f, 0x74, 0x70,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x22, 0x38, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x4f,
	0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x43, 0x0a, 0x13,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x22, 0x2c, 0x0a, 0x14, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54,
	0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x32,
	0xcf, 0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5f, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54, 0x50, 0x12,
	0x26, 0x2e, 0x64, 0x71, 0x78, 0x30, 0x2e, 0x74, 0x6f, 0x74, 0x70, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54, 0x50,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x71, 0x78, 0x30, 0x2e, 0x74,
	0x6f, 0x74, 0x70, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5f, 0x0a, 0x0c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54, 0x50,
	0x12, 0x26, 0x2e, 0x64, 0x71, 0x78, 0x30, 0x2e, 0x74, 0x6f, 0x74, 0x70, 0x5f, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54,
	0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x64, 0x71, 0x78, 0x30, 0x2e,
	0x74, 0x6f, 0x74, 0x70, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x6f, 0x74, 0x70, 0x5f,
	0x61, 0x75, 0x74, 0x68, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_auth_proto_rawDescOnce sync.Once
	file_proto_v1_auth_proto_rawDescData = file_proto_v1_auth_proto_rawDesc
)

func file_proto_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_auth_proto_rawDescData)
	})
	return file_proto_v1_auth_proto_rawDescData
}

var file_proto_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_auth_proto_goTypes = []any{
	(*GenerateTOTPRequest)(nil),  // 0: dqx0.totp_auth.v1.GenerateTOTPRequest
	(*GenerateTOTPResponse)(nil), // 1: dqx0.totp_auth.v1.GenerateTOTPResponse
	(*ValidateTOTPRequest)(nil),  // 2: dqx0.totp_auth.v1.ValidateTOTPRequest
	(*ValidateTOTPResponse)(nil), // 3: dqx0.totp_auth.v1.ValidateTOTPResponse
}
var file_proto_v1_auth_proto_depIdxs = []int32{
	0, // 0: dqx0.totp_auth.v1.AuthService.GenerateTOTP:input_type -> dqx0.totp_auth.v1.GenerateTOTPRequest
	2, // 1: dqx0.totp_auth.v1.AuthService.ValidateTOTP:input_type -> dqx0.totp_auth.v1.ValidateTOTPRequest
	1, // 2: dqx0.totp_auth.v1.AuthService.GenerateTOTP:output_type -> dqx0.totp_auth.v1.GenerateTOTPResponse
	3, // 3: dqx0.totp_auth.v1.AuthService.ValidateTOTP:output_type -> dqx0.totp_auth.v1.ValidateTOTPResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_auth_proto_init() }
func file_proto_v1_auth_proto_init() {
	if File_proto_v1_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_auth_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateTOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_auth_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateTOTPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_auth_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ValidateTOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_auth_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ValidateTOTPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_v1_auth_proto = out.File
	file_proto_v1_auth_proto_rawDesc = nil
	file_proto_v1_auth_proto_goTypes = nil
	file_proto_v1_auth_proto_depIdxs = nil
}
